exam/exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),

]

exam/polls/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
urlpatterns = [
    path('vacation/', views.vacation),
    path('show/', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),

    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

exam/polls/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class Vacation(models.Model):
    description = models.CharField(max_length=200)
    dateFrom = models.DateTimeField()
    dateTo = models.DateTimeField()
    employee = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

    def dateEditable(self):
        now = timezone.now()
        return self.dateFrom > now

    # def save(self, *args, **kwargs):
    #     # Current datetime for the timezone of your variable
    #     if self.dateTo < datetime.datetime.today() or self.dateFrom < datetime.datetime.today():
    #         raise ValidationError("The date cannot be in the past!")
    #     super(Vacation, self).save(*args, **kwargs)

    def duration(self):
        return abs((self.dateFrom - self.dateTo).days)

exam/polls/forms.py
from django import forms
from .models import Vacation
from django.core.exceptions import ValidationError
from django.utils import timezone


class VacationForm(forms.ModelForm):
    dateFrom = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        }))
    dateTo = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker2'
        }))
    description = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))

    def clean(self):
        cleaned_data = super().clean()
        date1 = cleaned_data['dateFrom']
        date2 = cleaned_data['dateTo']
        if date1 > date2:
            self.add_error(
                'dateTo', "starting date is longer than ending date")
        if date1 < timezone.now():
            self.add_error('dateFrom', 'Date cannot be in the past')

    class Meta:
        model = Vacation
        exclude = ['employee']   # Will be taken from the request

exam/polls/views.py
import re
from .models import Vacation
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .forms import VacationForm
from django.core import serializers

# Create your views here.


@login_required
def vacation(request):
    if request.method == "POST":
        form = VacationForm(request.POST)
        if form.is_valid():
            try:
                instance = form.save(commit=False)
                instance.employee = request.user
                instance.save()
                return redirect('/show')
            except Exception:
                return redirect('/show')
    else:
        form = VacationForm(initial={'employee': request.user.id})
    return render(request, 'employee/index.html', {'form': form})


@login_required
def show(request):
    # vacations = serializers.serialize(
    #     "json", Vacation.objects.filter(employee=request.user.id))
    vacations = Vacation.objects.filter(employee=request.user.id)
    return render(request, 'employee/show.html', {'vacations': vacations})


@login_required
def edit(request, id):
    vacation = Vacation.objects.get(id=id)
    if not vacation.dateEditable():
        return redirect('/show')
    return render(request, 'employee/edit.html', {'form': vacation})


@login_required
def update(request, id):
    vacation = Vacation.objects.get(id=id)
    if not vacation.dateEditable():
        return redirect('/show')
    form = VacationForm(request.POST, instance=vacation)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, 'employee/edit.html', {'form': vacation, 'errors': form.errors})


@login_required
def destroy(request, id):
    vacation = Vacation.objects.get(id=id)
    if vacation.dateEditable():
        vacation.delete()
    return redirect('/show')


# login
@login_required
def logout_view(request):
    logout(request)


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/show')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

exam/polls/templates/base.html
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>

    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />

    <!-- 3rd party CSS -->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    />

    <!-- DataTables CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css"
    />
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/show">MyDjangoApp</a>
        </div>
        <div class="navbar-header">

            <a class="navbar-brand" href="/logout">Logout</a>
        </div>
        </div>
      </div>
    </nav>
    <main class="main p-2 overflow-auto">
      <!-- Specific content of the page -->
      {% block content %} {% endblock content %}
    </main>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Bootstrap & Popper -->

    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>

    <!-- Custom script -->
    {% block js %} {% endblock js %}
  </body>
</html>

exam/polls/templates/employee/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
      integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
      integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
      crossorigin="anonymous"
    ></script>

    <!-- Font Awesome -->
    <link
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />

    <!-- Moment.js -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
      integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA="
      crossorigin="anonymous"
    ></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
      integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs="
      crossorigin="anonymous"
    />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
      integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4="
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <form method="POST" class="post-form" action="/update/{{form.id}}">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Update Vacation</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label"> Description:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="description"
              id="id_ename"
              maxlength="100"
              class="form-control"
              value="{{ form.description }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-2 col-form-label">Start Date:</label>
          <div
            class="col-6 input-group date"
            id="datetimepicker2"
            data-target-input="nearest"
          >
            <input
              type="text"
              name="dateFrom"
              class="form-control datetimepicker-input"
              data-target="#datetimepicker2"
              id="id_dateFrom"
              value="{{form.dateFrom|date:'d/m/Y h:m'}}"
            />
            <div
              class="input-group-append"
              data-target="#datetimepicker2"
              data-toggle="datetimepicker"
            >
              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-2 col-form-label">End Date:</label>
          <div
            class="input-group date col-6"
            id="datetimepicker1"
            data-target-input="nearest"
          >
            <input
              type="text"
              name="dateTo"
              class="form-control datetimepicker-input"
              data-target="#datetimepicker1"
              id="id_dateTo"
              value="{{form.dateTo|date:'d/m/Y h:m'}}"
            />
            <div
              class="input-group-append"
              data-target="#datetimepicker1"
              data-toggle="datetimepicker"
            >
              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
            </div>
          </div>
        </div>
        {% if errors %}
        <div style="color: red">{{ errors }}</div>
        {% endif %}
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
        </div>
      </div>
    </form>
    <script>
      $(function () {
        $("#datetimepicker1").datetimepicker({
          format: "DD/MM/YYYY HH:mm",
        });
        $("#datetimepicker2").datetimepicker({
          format: "DD/MM/YYYY HH:mm",
        });
      });
    </script>
  </body>
</html>

exam/polls/templates/employee/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
      integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
      integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
      crossorigin="anonymous"
    ></script>

    <!-- Font Awesome -->
    <link
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />

    <!-- Moment.js -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
      integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA="
      crossorigin="anonymous"
    ></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
      integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs="
      crossorigin="anonymous"
    />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
      integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4="
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    {% block content %}
    <h2>Add Vaction</h2>
    <form method="post" class="post-form">
      {% csrf_token %}
      <div class="row">
        <label class="col-sm-2 col-form-label">Starting date:</label>

        <div
          class="input-group date col-md-6"
          id="datetimepicker1"
          data-target-input="nearest"
        >
          {{ form.dateFrom }}
          <div
            class="input-group-append"
            data-target="#datetimepicker1"
            data-toggle="datetimepicker"
          >
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
      <div
        style="width: 100%; margin-top: 0.25rem; font-size: 80%; color: #dc3545"
      >
        {{form.dateFrom.errors}}
      </div>

      <div class="row">
        <label class="col-sm-2 col-form-label">Ending date:</label>

        <div
          class="input-group date col-md-6"
          id="datetimepicker2"
          data-target-input="nearest"
        >
          {{ form.dateTo }}
          <div
            class="input-group-append"
            data-target="#datetimepicker2"
            data-toggle="datetimepicker"
          >
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
      <div
        style="width: 100%; margin-top: 0.25rem; font-size: 80%; color: #dc3545"
      >
        {{form.dateTo.errors}}
      </div>

      <div class="row">
        <label class="col-sm-2 col-form-label">Description:</label>

        <div class="input-group col-md-6">{{ form.description }}</div>
        <div class="">{{form.description.errors}}</div>
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </form>
    {% comment %}
    <form action="" method="post">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
    </form>
    {% endcomment %}
    <script>
      $(function () {
        $("#datetimepicker1").datetimepicker({
          format: "DD/MM/YYYY HH:mm",
        });
        $("#datetimepicker2").datetimepicker({
          format: "DD/MM/YYYY HH:mm",
        });
      });
    </script>

    {% endblock %}
  </body>
</html>

exam/polls/templates/employee/show.html
{% extends 'base.html' %} <-- inherit the general template {% load static %}
{%block content %}
<div class="row">
  <div class="col-sm">
    <table id="table_db" class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Description</th>
          <th scope="col">From</th>
          <th scope="col">Duration</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for k in vacations %}
        <tr>
          <td>{{ k.description }}</td>
          <td>{{ k.dateFrom }}</td>
          <td>{{ k.duration }}</td>
          <td>
            {% if k.dateEditable %}<a href="/edit/{{ k.id }}"
              ><span class="glyphicon glyphicon-pencil">Edit</span></a
            >
            <a href="/delete/{{ k.id }}">Delete</a>{% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<center>
  <a href="/vacation" class="btn btn-primary">Add New Record</a>
</center>

{% endblock content %} {% block js %}

<script>
  $(document).ready(function () {
    $("#table_db").DataTable({
      paging: true,
      autoWidth: true,
      ordering: true,
    });
  });
</script>

{% endblock js %}